# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bdafb5d2f48d053c6e24b6b49d61fe8c0e2ea045203e75f593592902dcea5bcfb2c14ad6ef4696d3cfea789300edde134ae40c8562284cf888110308e83633f

test:
  secret_key_base: 4d4ef197ddedf72ced9baff3b4a909cd6a322cf1f3ca016034e8fcfc6070beebf5d36eac8ef02a801c75bcfe332e2b0dcc97ffc8e4e52b8d067ed0737c6b8c3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
